# Configure environment
osx_image: xcode9.2
language: objective-c

# Paths
podfile: ./Podfile

# Build script
script:
  - xcodebuild -scheme Squad Mortar Calculator -project Squad Mortar Calculator.xcodeproj -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=11.2' build test
