# Configure environment
osx_image: xcode9
language: objective-c
xcode_sdk: iphonesimulator8.3

# Paths
podfile: ./Podfile
xcode_project: Squad Mortar Calculator.xcodeproj
xcode_scheme: Squad Mortar CalculatorTests

# Build script
script:
  - xcodebuild clean build test -workspace Squad\ Mortar\ Calculator.xcworkspace -scheme Squad\ Mortar\ CalculatorTests CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO

# After tests have completed send report to codecov for coverage review
after_success:
  - bash <(curl -s https://codecov.io/bash)
