# Configure environment
osx_image: xcode9.2
language: objective-c
xcode_sdk: iphonesimulator11.2

# Paths
podfile: ./Podfile

# Build script
script:
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild clean build test -workspace Squad\ Mortar\ Calculator.xcworkspace -scheme Squad\ Mortar\ Calculator -configuration Release -enableCodeCoverage YES -destination "platform=iOS Simulator,name=iPhone 7,OS=11.2" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO

# After tests have completed send report to codecov for coverage review
after_success:
  - bash <(curl -s https://codecov.io/bash)
