# Configure environment
osx_image: xcode9.2
language: objective-c

# Paths
podfile: ./Podfile

# Build script
script:
  - xcodebuild clean build test -project Squad\ Mortar\ Calculator.xcodeproj -scheme Squad\ Mortar\ Calculator
